#!/usr/bin/env python3
"""Relay Emesent's namespaced TF topics onto conventional ROS 1 TF topics."""

import rospy
from tf2_msgs.msg import TFMessage


class TfRelay:
    def __init__(self):
        self._dynamic = rospy.Publisher("/tf", TFMessage, queue_size=20)
        self._static = rospy.Publisher("/tf_static", TFMessage, queue_size=1, latch=True)
        self._static_by_child = {}
        self._dynamic_sub = rospy.Subscriber(
            "/cortex/tf", TFMessage, self._relay_dynamic, queue_size=20
        )
        self._static_sub = rospy.Subscriber(
            "/cortex/tf_static", TFMessage, self._relay_static, queue_size=10
        )

    def _relay_dynamic(self, message):
        self._dynamic.publish(message)

    def _relay_static(self, message):
        # A latched ROS 1 publisher retains only its last message. Accumulate
        # by child frame so a late subscriber receives the complete static tree
        # even if Cortex delivered it in several messages.
        for transform in message.transforms:
            self._static_by_child[transform.child_frame_id] = transform
        aggregate = TFMessage(transforms=list(self._static_by_child.values()))
        self._static.publish(aggregate)


if __name__ == "__main__":
    rospy.init_node("hovermap_tf_relay")
    relay = TfRelay()
    rospy.loginfo("Relaying /cortex/tf and /cortex/tf_static to standard TF topics")
    rospy.spin()
